FROM node:lts-bullseye-slim as base

ENV NODE_ENV=development

WORKDIR /usr/src/api

RUN npm install -g pnpm

# Build
FROM base as build

COPY package*.json ./

RUN pnpm install

# Run
FROM base

COPY --from=build /usr/src/api/node_modules /usr/src/api/node_modules

CMD ["pnpm", "run", "dev"]