FROM mcr.microsoft.com/playwright as base

ENV NODE_ENV=development

WORKDIR /usr/src/api

RUN npm install -g pnpm
RUN npm install -g rimraf

# Build
FROM base as build

COPY package*.json ./

RUN pnpm install 

# Run
FROM base

RUN npx -y playwright install --with-deps

COPY --from=build /usr/src/api/node_modules /usr/src/api/node_modules 

CMD ["pnpm", "run", "dev"]