export const SlotSchemaFixtures: { name: string }[] = [
  { name: "Tête" },
  { name: "Cou" },
  { name: "Epaule" },
  { name: "Dos" },
  { name: "Torse" },
  { name: "Poignets" },
  { name: "Mains" },
  { name: "Taille" },
  { name: "Jambes" },
  { name: "Pieds" },
  { name: "Doigt" },
  { name: "Bijou" },
  { name: "Relique" },
  { name: "Main gauche" },
  { name: "Main droite" },
  { name: "Tenu en main gauche" },
  { name: "A une main" },
  { name: "Deux mains" },
  { name: "A distance" },
  { name: "Bouclier" },
];

export const stuffGearSchemaFixtures: { name: string }[] = [
  { name: "Bijou" },
  { name: "Armures en tissu" },
  { name: "Armures en cuir" },
  { name: "Armures en plaques" },
  { name: "Accessoire pour main gauche" },
  { name: "Armures en mailles" },
  { name: "Bouclier" },
  { name: "Libram" },
  { name: "Totem" },
  { name: "Cape" },
  { name: "Arbalète" },
  { name: "Masse à une main" },
  { name: "Masse à deux mains" },
  { name: "Bâton" },
  { name: "Dague" },
  { name: "Épée à une main" },
  { name: "Épée à deux mains" },
  { name: "Hache à une main" },
  { name: "Hache à deux mains" },
  { name: "Arme de pugilat" },
  { name: "Armes d'hast" },
  { name: "Jeton" },
  { name: "Quête" },
  { name: "Anneau" },
  { name: "Arme à feu" },
  { name: "Arc" },
  { name: "Schéma d'ingénierie" },
];

export const DungeonSchemaFixtures: { name: string; url: string }[] = [
  {
    name: "Les profondeurs de Brassenoire",
    url: "https://www.wowhead.com/classic/fr/zone=719/profondeurs-de-brassenoire",
  },
  {
    name: "Gnomeregan",
    url: "https://www.wowhead.com/classic/fr/zone=721/gnomeregan",
  },
  {
    name: "Le temple d'Atal'Hakkar",
    url: "https://www.wowhead.com/classic/fr/zone=1477/le-temple-datalhakkar",
  },
];
